### وارد کردن کتابخانه های مرتبط

In [1]:
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd

### ساخت ماتریس

In [1]:
A = array([
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
])
print(A)

NameError: name 'array' is not defined

فاکتور سازی

In [3]:
U, s, V = svd(A)

In [5]:
Sigma = zeros((A.shape[0], A.shape[1]))

ساخت ماتریس قطری n * n

In [6]:
Sigma[:A.shape[0], :A.shape[0]] = diag(s)

ساخت فاکتور

In [7]:
n_elements = 2
Sigma = Sigma[:, :n_elements]
V = V[:n_elements, :]

In [8]:
B = U.dot(Sigma.dot(V))
print(B)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]

پیاده سازی  کاهش ابعاد

In [9]:
T = U.dot(Sigma)
print(T)

[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]

In [10]:
import pandas as pd
import numpy as np

In [11]:
shahin = pd.read_csv('C:\\Users\\ShahinN\\Desktop\\data.txt')
shahin.head()

,A,B,C,D,E,F,G,H,I,J,K,L,M,N
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [12]:
shahin2 = shahin[['B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']]
shahin2.head()

       B     C     D     E    F     G     H     I
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39

In [13]:
A = shahin.values
print(A)

[[1.000e+00 1.423e+01 1.710e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.000e+00 1.320e+01 1.780e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.000e+00 1.316e+01 2.360e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [3.000e+00 1.327e+01 4.280e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [3.000e+00 1.317e+01 2.590e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [3.000e+00 1.413e+01 4.100e+00 ... 6.100e-01 1.600e+00 5.600e+02]]

In [14]:
U, s, V = svd(A)

In [15]:
n_elements = 2
Sigma = A[:, :n_elements]
V = V[:n_elements, :]

In [16]:
B= U.dot(Sigma.dot(V))

In [17]:
T = U.dot(Sigma)
print(T)

[[-2.57592213e+01 -1.46823276e+02]
 [ 4.29539498e+00 -2.87855605e+01]
 [-4.89339918e-01 -5.78058685e+00]
 [ 1.06130937e-01 -8.19120702e-01]
 [-1.78823356e+00 -2.96983294e+01]
 [ 1.44281551e+00  1.81111845e-01]
 [ 1.79877595e+00  8.09849555e+00]
 [-3.51280892e-02 -5.98098525e+00]
 [-5.29379370e-01 -8.01164377e+00]
 [-2.05128964e+00 -1.69475087e+01]
 [ 1.76677976e-02 -6.87752831e+00]
 [-1.89236069e+00 -1.70945254e+01]
 [-4.47471092e+00 -3.32689985e+01]
 [-2.41415066e-01 -1.18411707e+01]
 [ 4.56488130e-01  6.75709751e+00]
 [ 8.19650723e-03 -2.72682237e-01]
 [ 4.19262441e-01  4.78314480e+00]
 [ 2.60163081e-02  6.64157326e-01]
 [-2.01484852e-01  4.68566337e-01]
 [ 6.81093310e-01  4.76128376e+00]
 [ 1.17636519e+00  7.31862026e+00]
 [ 1.00895961e+00  7.95861931e+00]
 [ 9.90942364e-01  8.20560090e+00]
 [ 7.17211693e-01  5.49011227e+00]
 [ 7.93082842e-01  5.81157386e+00]
 [ 7.46958954e-01  4.72189541e+00]
 [ 3.76519394e-01  5.05167136e+00]
 [ 3.87114795e-01  5.94234518e+00]
 [ 2.67590762e-01  1.54356088e+00]
 [ 1.18072295e+00  1.07060930e+01]
 [-3.26852826e-02  1.30137343e+00]
 [ 3.14183628e-01  4.42402265e+00]
 [ 5.15707445e-01  5.42359259e+00]
 [ 4.76120975e-01  3.68633462e+00]
 [ 4.42173300e-01  4.04271110e+00]
 [ 7.29653142e-01  5.72182366e+00]
 [ 1.31814309e-01  2.09187826e-01]
 [-7.29743053e-02  4.59156594e-01]
 [-1.84640371e-02  6.58715603e-01]
 [ 1.16721955e+00  9.21024428e+00]
 [ 1.12163735e+00  8.29967665e+00]
 [ 4.66133130e-01  7.11862810e+00]
 [ 3.33743459e-01  3.30271235e+00]
 [ 7.70082420e-01  7.74314483e+00]
 [ 9.77881766e-01  8.20655025e+00]
 [ 7.85830551e-01  8.72139914e+00]
 [ 5.55944661e-01  7.14739153e+00]
 [ 7.37524168e-01  6.75830622e+00]
 [ 6.44022772e-01  6.81098158e+00]
 [ 7.10547598e-01  6.16732077e+00]
 [ 6.59038482e-01  6.29461958e+00]
 [ 6.06581431e-01  5.71502435e+00]
 [ 9.05395909e-02  1.47802526e+00]
 [ 4.22282162e-01  4.81371072e+00]
 [ 1.00134674e+00  7.93831430e+00]
 [ 9.43932174e-01  7.86813712e+00]
 [ 9.93510533e-01  7.96115483e+00]
 [-6.85225581e-02  7.42462154e-01]
 [ 1.11780892e-01  2.18057823e+00]
 [-6.58546395e-01 -5.48968355e+00]
 [-8.89596300e-01 -7.73693798e+00]
 [-4.12132200e-01 -4.49791048e+00]
 [-6.64886559e-01 -6.52442473e+00]
 [-1.43069651e+00 -1.48050647e+01]
 [-9.43222077e-01 -1.16032997e+01]
 [-6.56165449e-01 -7.04511074e+00]
 [-3.48085648e-01 -4.17801762e+00]
 [ 3.47683825e-02 -2.52512629e+00]
 [-6.47828076e-01 -5.08233783e+00]
 [ 1.38382427e+00  6.61040002e+00]
 [ 4.94383161e-01  4.94416831e+00]
 [-1.19085181e+00 -1.25943466e+01]
 [-1.12117250e-01 -2.17420889e+00]
 [-3.36427243e-01 -6.03617129e+00]
 [-6.15467737e-01 -6.56618490e+00]
 [-4.12288265e-01 -5.97870288e+00]
 [-3.42563152e-01 -5.19582441e+00]
 [ 3.02013583e-01  1.10914173e+00]
 [ 1.08237830e+00  7.11421490e+00]
 [-3.87798536e-01 -3.68893110e+00]
 [-7.67999279e-01 -1.02649453e+01]
 [-2.14738303e-01 -2.86161584e+00]
 [-6.55993135e-01 -6.63674391e+00]
 [ 3.90520346e-01  5.75670529e+00]
 [ 5.43831220e-01  2.24085992e+00]
 [-9.84602968e-02 -4.08936519e+00]
 [-5.96908470e-01 -6.35270468e+00]
 [-2.76618300e-01 -5.29479700e+00]
 [-2.29996003e-02 -1.41559730e-01]
 [-1.26469962e-01 -9.67055086e-01]
 [-2.85845258e-02 -5.19153973e-02]
 [ 5.79684456e-01  3.30258154e+00]
 [ 2.94350313e-01  3.54911684e+00]
 [-2.11801544e-01 -3.85881167e+00]
 [-1.02591113e+00 -1.24045787e+01]
 [ 1.09392113e+00  6.87114512e+00]
 [ 4.07788149e-01 -2.10980031e-01]
 [-8.04032198e-01 -8.42577498e+00]
 [-1.34931506e+00 -1.21362901e+01]
 [-8.05066256e-01 -7.03572807e+00]
 [-3.61688263e-01 -4.45596594e+00]
 [ 3.93261849e-01  2.34122433e+00]
 [ 2.56056307e-01  5.85228988e-01]
 [-3.92983201e-01 -3.39539013e+00]
 [ 4.07891299e-01  2.60674934e+00]
 [ 1.09892290e+00  8.75668917e+00]
 [ 4.82732981e-01  2.89010737e+00]
 [ 5.05220529e-01  4.54358318e+00]
 [ 5.90483574e-01  3.60148048e+00]
 [-8.97629417e-02 -2.27767986e+00]
 [ 6.12625785e-01  6.17658117e+00]
 [-6.41543892e-01 -6.13949201e+00]
 [-3.78832836e-01 -5.00316540e+00]
 [-8.57548045e-01 -9.34338736e+00]
 [-3.45241892e-01 -4.75530187e+00]
 [-1.07232241e+00 -1.19365302e+01]
 [ 5.00202207e-01  2.69428981e+00]
 [ 2.23925616e-01 -9.09003853e-01]
 [ 1.39518085e-01  2.91043273e+00]
 [ 4.52544168e-01  4.96554812e+00]
 [ 2.43043132e-02 -8.44036981e-01]
 [-4.86053838e-01 -9.01863396e+00]
 [ 2.21644729e-01  1.39642635e+00]
 [ 4.74242684e-02  2.89848326e+00]
 [ 3.41633179e-01  2.96827631e+00]
 [-1.75168443e-01 -2.52125878e+00]
 [-1.76946828e-01 -2.09011563e+00]
 [-1.85105133e-01 -1.99997601e+00]
 [-1.54998557e-02 -8.14598448e-01]
 [-1.39368610e-01  1.11868977e+00]
 [-7.73087980e-01 -8.18807654e+00]
 [-7.67371237e-01 -7.31862853e+00]
 [-5.69991916e-01 -5.40852964e+00]
 [-1.24990123e+00 -1.07892471e+01]
 [-3.69897470e-01 -1.86664272e+00]
 [ 1.10230530e-02  1.07448995e+00]
 [-7.79015032e-01 -3.29551501e+00]
 [-4.48220213e-01 -1.70686982e+00]
 [-1.36327948e-01  7.22189761e-01]
 [-5.88354721e-01 -5.19040536e+00]
 [ 5.48597564e-02  3.12085701e-01]
 [ 2.38353116e-01  2.38987412e+00]
 [-4.57674232e-01 -3.97257518e+00]
 [-6.58583855e-01 -3.50867851e+00]
 [ 4.75970231e-01  3.30117521e+00]
 [ 1.83309318e-01  4.63045294e+00]
 [-2.94273392e-01  6.86834902e-01]
 [-5.84543053e-03  1.62999769e+00]
 [ 4.85156894e-02  1.55499886e+00]
 [-2.44752447e-03 -9.55632732e-01]
 [-1.74288983e-01 -3.76689250e+00]
 [ 2.26102352e-01 -1.16728176e+00]
 [-5.62462759e-01 -7.00600373e+00]
 [ 7.87570344e-01  7.72653899e+00]
 [ 6.52161996e-01  5.10668023e+00]
 [ 2.87178191e-01  5.93763519e+00]
 [ 2.77242268e-01  3.60329184e+00]
 [ 7.22518981e-02  2.14799652e+00]
 [ 8.47760368e-01  6.36313977e+00]
 [ 4.40441165e-01  3.14631064e+00]
 [-5.05693139e-01 -3.11901041e+00]
 [-4.54103361e-01 -3.72962469e+00]
 [ 7.69602215e-02  1.59247732e-01]
 [-2.98042784e-03  5.69548772e-01]
 [ 2.05815467e-01  1.41291262e+00]
 [ 1.39351294e-01  2.86160197e+00]
 [ 7.25398744e-02 -7.30338111e-01]
 [ 7.67327642e-02  7.18908532e-02]
 [ 2.93530076e-01  1.66234945e+00]
 [-2.24837069e-01 -2.99360015e+00]
 [-5.11079192e-03 -6.64740373e-01]
 [ 2.27735837e-01  7.28308919e-01]
 [ 2.98236949e-01  2.73345725e+00]
 [ 1.00015400e-01  3.87100438e+00]
 [-8.91727078e-02  6.97112964e-01]
 [ 7.20259068e-01  6.32014667e+00]
 [ 8.49071767e-01  6.93622696e+00]
 [ 7.55635499e-02  1.91515503e+00]]

In [18]:
T.shape

(178, 2)

In [19]:
type(T)

numpy.ndarray

In [20]:
shahin_svd = pd.DataFrame(T, columns= ['فاکتور1', 'فاکتور 2'])
shahin_svd.head()

     فاکتور1    فاکتور 2
0 -25.759221 -146.823276
1   4.295395  -28.785560
2  -0.489340   -5.780587
3   0.106131   -0.819121
4  -1.788234  -29.698329

In [22]:
shahin_final = shahin[['A']]
shahin_final = shahin_final.join(shahin_svd)
shahin_final.head()

   A    فاکتور1    فاکتور 2
0  1 -25.759221 -146.823276
1  1   4.295395  -28.785560
2  1  -0.489340   -5.780587
3  1   0.106131   -0.819121
4  1  -1.788234  -29.698329

In [23]:
shahin_final.to_csv('C:\\Users\\ShahinN\\Desktop\\کاهش ابعاد دیتاست.csv')